package mod.azure.azurecompat.util;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.robertx22.api.MineAndSlashAPI;
import com.robertx22.config.non_mine_items.ConfigItem;
import com.robertx22.database.gearitemslots.Axe;
import com.robertx22.database.gearitemslots.Bow;
import com.robertx22.database.gearitemslots.Hammer;
import com.robertx22.database.gearitemslots.Sword;

public class SpartanWeaponsCompat {

	public String MODID = "spartanweaponry:";

	public SpartanWeaponsCompat() {
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "dagger_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longsword_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "katana_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "saber_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "rapier_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "greatsword_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "caestus",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "caestus_studded",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "club_wood",
				new ConfigItem().setType(new Hammer()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "club_studded",
				new ConfigItem().setType(new Hammer()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_wood",
				new ConfigItem().setType(new Hammer()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_stone",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_copper",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_tin",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_bronze",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_iron",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_steel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_silver",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_gold",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_lead",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_electrum",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_nickel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_invar",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_diamond",
				new ConfigItem().setType(new Hammer()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "hammer_platinum",
				new ConfigItem().setType(new Hammer()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_wood",
				new ConfigItem().setType(new Hammer()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_stone",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_copper",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_tin",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_bronze",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_iron",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_steel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_silver",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_gold",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_lead",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_electrum",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_nickel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_invar",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_diamond",
				new ConfigItem().setType(new Hammer()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "warhammer_platinum",
				new ConfigItem().setType(new Hammer()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_wood",
				new ConfigItem().setType(new Axe()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_stone",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_copper",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_tin",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_bronze",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_iron",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_steel",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_silver",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_gold",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_lead",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_electrum",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_nickel",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_invar",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_diamond",
				new ConfigItem().setType(new Axe()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "spear_platinum",
				new ConfigItem().setType(new Axe()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_wood",
				new ConfigItem().setType(new Hammer()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_stone",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_copper",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_tin",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_bronze",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_iron",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_steel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_silver",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_gold",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_lead",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_electrum",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_nickel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_invar",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_diamond",
				new ConfigItem().setType(new Hammer()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "halberd_platinum",
				new ConfigItem().setType(new Hammer()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_wood",
				new ConfigItem().setType(new Hammer()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_stone",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_copper",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_tin",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_bronze",
				new ConfigItem().setType(new Hammer()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_iron",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_steel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_silver",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_gold",
				new ConfigItem().setType(new Hammer()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_lead",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_electrum",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_nickel",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_invar",
				new ConfigItem().setType(new Hammer()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_diamond",
				new ConfigItem().setType(new Hammer()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "lance_platinum",
				new ConfigItem().setType(new Hammer()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longbow_wood",
				new ConfigItem().setType(new Bow()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longbow_leather",
				new ConfigItem().setType(new Bow()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longbow_iron",
				new ConfigItem().setType(new Bow()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "longbow_diamond",
				new ConfigItem().setType(new Bow()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "crossbow_wood",
				new ConfigItem().setType(new Bow()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "crossbow_leather",
				new ConfigItem().setType(new Bow()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "crossbow_iron",
				new ConfigItem().setType(new Bow()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "crossbow_diamond",
				new ConfigItem().setType(new Bow()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "throwing_knife",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "throwing_axe",
				new ConfigItem().setType(new Axe()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_wood",
				new ConfigItem().setType(new Axe()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_stone",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_copper",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_tin",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_bronze",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_iron",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_steel",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_silver",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_gold",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_lead",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_electrum",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_nickel",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_invar",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_diamond",
				new ConfigItem().setType(new Axe()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "javelin_platinum",
				new ConfigItem().setType(new Axe()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_wood",
				new ConfigItem().setType(new Bow()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_stone",
				new ConfigItem().setType(new Bow()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_copper",
				new ConfigItem().setType(new Bow()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_tin",
				new ConfigItem().setType(new Bow()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_bronze",
				new ConfigItem().setType(new Bow()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_iron",
				new ConfigItem().setType(new Bow()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_steel",
				new ConfigItem().setType(new Bow()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_silver",
				new ConfigItem().setType(new Bow()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_gold",
				new ConfigItem().setType(new Bow()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_lead",
				new ConfigItem().setType(new Bow()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_electrum",
				new ConfigItem().setType(new Bow()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_nickel",
				new ConfigItem().setType(new Bow()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_invar",
				new ConfigItem().setType(new Bow()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_diamond",
				new ConfigItem().setType(new Bow()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "boomrang_platinum",
				new ConfigItem().setType(new Bow()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_wood",
				new ConfigItem().setType(new Axe()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_stone",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_copper",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_tin",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_bronze",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_iron",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_steel",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_silver",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_gold",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_lead",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_electrum",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_nickel",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_invar",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_diamond",
				new ConfigItem().setType(new Axe()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "battleaxe_platinum",
				new ConfigItem().setType(new Axe()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_wood",
				new ConfigItem().setType(new Sword()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_stone",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_copper",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_tin",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_bronze",
				new ConfigItem().setType(new Sword()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_iron",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_steel",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_silver",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_gold",
				new ConfigItem().setType(new Sword()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_lead",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_electrum",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_nickel",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_invar",
				new ConfigItem().setType(new Sword()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_diamond",
				new ConfigItem().setType(new Sword()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "mace_platinum",
				new ConfigItem().setType(new Sword()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_wood",
				new ConfigItem().setType(new Axe()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_stone",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_copper",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_tin",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_bronze",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_iron",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_steel",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_silver",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_gold",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_lead",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_electrum",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_nickel",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_invar",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_diamond",
				new ConfigItem().setType(new Axe()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "glaive_platinum",
				new ConfigItem().setType(new Axe()).setMinLevel(60).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_wood",
				new ConfigItem().setType(new Axe()).setMaxLevel(10).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_stone",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_copper",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_tin",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_bronze",
				new ConfigItem().setType(new Axe()).setMaxLevel(20).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_iron",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_steel",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_silver",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_gold",
				new ConfigItem().setType(new Axe()).setMaxLevel(30).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_lead",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_electrum",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_nickel",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_invar",
				new ConfigItem().setType(new Axe()).setMaxLevel(40).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_diamond",
				new ConfigItem().setType(new Axe()).setMinLevel(50).setdropsAsLoot(false));
		MineAndSlashAPI.addCompatibleItem(MODID + "staff_platinum",
				new ConfigItem().setType(new Axe()).setMinLevel(60).setdropsAsLoot(false));
	}
}